### ISSUE TITLE
``calculate_distance`` method should truncate list at ``r_max``

### ISSUE THREAD

**Issue by hdsassnick** [aim2dat/aim2dat#82]
I think it would be more intuitive if ``r_max`` actually defines the cutoff distance for the output list (for ``use_supercell=True``).

@Scemp, @t-reents what do you think?

**Comment by t-reents** [comment]
Yes, I think this change could make sense. I don't have a strong opinion here, but I agree that the current approach is not super intuitive.

**Comment by hdsassnick** [comment]
In practice, I think it makes no difference. I only noticed it when writing a more detailed documentation on the method and the output was extensively long as it always uses a minimum of a 3x3x3 supercell.

I will create a PR on this soon..
